server:
  port: 8080
  servlet:
    context-path: /med-soft


spring:
  profiles:
    active: local
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties.hibernate.jdbc.lob.non_contextual_creation: true
    properties.hibernate.default_schema=yourschema: medsoft
    
  datasource:
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE