server:
  port: 8080
  servlet:
    context-path: /medsoft


spring:
  profiles:
    active: local
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties.hibernate.jdbc.lob.non_contextual_creation: true
    properties.hibernate.default_schema=yourschema: medsoft
    
  datasource:
    driver-class-name: org.postgresql.Driver

logging:
  level:
    root: error
    #org.hibernate.SQL: ERROR
    #org.hibernate.type: ERROR